In [1]:
import numpy as np
np.__version__

'1.19.5'

In [2]:
a1 = np.array([1, 2, 3])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2])
a1[0] = 4
print(a1)

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1 2 3
[4 2 3]


In [3]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2)
print(a2.shape)
print(a2[0, 0], a2[1, 1], a2[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [4]:
a3 = np.array([[[1, 2, 3], [4, 5, 6]],
               [[1, 2, 3], [4, 5, 6]],
               [[1, 2, 3], [4, 5, 6]]])
print(a3)
print(a3.shape)
print(type(a3))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(3, 2, 3)
<class 'numpy.ndarray'>


In [5]:
# zeros
print(np.zeros(10))

print(end = '\n\n')

# ones
print(np.ones(10))
print(np.ones((3, 3)))

print(end = '\n\n')

# full
print(np.full((3, 3), 5))

print(end = '\n\n')

# eye
print(np.eye(5))

print(end = '\n\n')

# tri
print(np.tri(3))

print(end = '\n\n')

# empty
print(np.empty(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[5 5 5]
 [5 5 5]
 [5 5 5]]


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
print(np.zeros_like(a1))
print(np.ones_like(a1))
print(np.full_like(a1, 10))

[0 0 0]
[1 1 1]
[10 10 10]


In [7]:
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [8]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
np.logspace(0.1, 1, 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

In [10]:
np.random.random((3, 3))

array([[0.60819073, 0.94248697, 0.67322309],
       [0.33052194, 0.78661078, 0.30655215],
       [0.04189388, 0.18192211, 0.68247912]])

In [11]:
np.random.randint(0, 10, (3, 3))

array([[5, 7, 5],
       [0, 6, 0],
       [8, 4, 8]])

In [12]:
np.random.normal(0, 1, (3, 3))

array([[ 0.34017889,  2.24915981,  0.84168104],
       [ 1.35404116, -1.91215571, -2.29438083],
       [-0.1337369 , -0.18805195, -0.02832951]])

In [13]:
np.random.rand(3, 3)

array([[0.36222434, 0.08234683, 0.92428276],
       [0.42319986, 0.86717414, 0.63080797],
       [0.85498831, 0.85169054, 0.20108817]])

In [14]:
np.random.randn(3, 3)

array([[ 0.46635759,  1.6765193 ,  2.45422   ],
       [-0.58682099, -0.98481492,  0.17805581],
       [-1.04410776,  1.08053401,  0.18898914]])

In [15]:
np.zeros(20, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones((3, 3), dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [17]:
np.full((3, 3), 1.0, dtype = float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.eye(5, dtype = bool)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [19]:
np.tri(3, dtype = bool)

array([[ True, False, False],
       [ True,  True, False],
       [ True,  True,  True]])

In [20]:
date = np.array('2020-01-01', dtype = np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [21]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [22]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [23]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns')
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')

In [24]:
datetime = np.array('2020-06-01 12:00:12', dtype = np.datetime64)
datetime

array('2020-06-01T12:00:12', dtype='datetime64[s]')

In [25]:
# array_info

def array_info(array):
    print(array)
    print("ndim:", array.ndim)
    print("dtype:", array.dtype)
    print("shape:", array.shape)
    print("size:", array.size)
    print("itemsize", array.itemsize)
    print("nbytes:", array.nbytes)
    print("strides:", array.strides)

In [26]:
a1 = np.array([4, 5, 6, 4, 5], dtype = np.int64)
array_info(a1)

[4 5 6 4 5]
ndim: 1
dtype: int64
shape: (5,)
size: 5
itemsize 8
nbytes: 40
strides: (8,)


In [27]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
dtype: int32
shape: (3, 3)
size: 9
itemsize 4
nbytes: 36
strides: (12, 4)


In [28]:
array_info(a3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
ndim: 3
dtype: int32
shape: (3, 2, 3)
size: 18
itemsize 4
nbytes: 72
strides: (24, 12, 4)


In [29]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])
print(a1[0:2])

[4 5 6 4 5]
4
6
5
4
[4 5]


In [30]:
print(a3)
print(a3[1, 1, 0])

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
4


In [31]:
print(a1)
print(a1[::2])
print(a1[::-1])

[4 5 6 4 5]
[4 6 5]
[5 4 6 5 4]


In [32]:
print(a2)
print(end = "\n\n")
print(a2[:1, :2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 2]]


In [33]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])

[4 5 6 4 5]
[5 6 5]


In [34]:
bi = np.random.randint(0, 2, (3, 3), dtype = bool)
print(bi)
print(a2[bi])

[[ True  True  True]
 [ True False  True]
 [ True  True False]]
[1 2 3 4 6 7 8]


In [35]:
# fancy indexing
print(a1)
print([a1[0], a1[2]])
idx = [0, 2]
print(a1[idx])
idx = np.array([[0, 1],
               [2, 0]])
print(a1[idx])
print(end = "\n\n")
print(a2)
row = np.array([0, 2])
col = np.array([1, 2])
print(a2[row, col])

[4 5 6 4 5]
[4, 6]
[4 6]
[[4 5]
 [6 4]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]


In [36]:
# insert
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
print(a1)
c1 = np.insert(a1, 2, 10)
print(c1)

[4 5 6 4 5]
[10  4  5  6  4  5]
[4 5 6 4 5]
[ 4  5 10  6  4  5]


In [37]:
print(a2)
b2 = np.insert(a2, 1, 10, axis = 0)
print(b2)
c2 = np.insert(a2, 1, 10, axis = 1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


In [38]:
a1[0] = 1
a1[1] = 2
a1[2] = 3
a1[:1] = 9
print(a1)
i = np.array([1, 3, 4])
a1[i] = 0
print(a1)
a1[i] += 4
print(a1)

[9 2 3 4 5]
[9 0 3 0 0]
[9 4 3 4 4]


In [39]:
print(a2)
a2[0, 0] = 1
a2[1, 1] = 2
a2[2, 2] = 3
a2[0] = 1
print(a2)
row = np.array([0, 1])
col = np.array([1, 2])
a2[row, col] = 0
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [4 2 6]
 [7 8 3]]
[[1 0 1]
 [4 2 0]
 [7 8 3]]


In [40]:
print(a1)
b1 = np.delete(a1, 1) # insert와 마찬가지로 원본배열은 그대로!
print(b1)
print(a2)
b2 = np.delete(a2, 1, axis = 0)
print(b2)
c2 = np.delete(a2, 1, axis = 1)
print(c2)

[9 4 3 4 4]
[9 3 4 4]
[[1 0 1]
 [4 2 0]
 [7 8 3]]
[[1 0 1]
 [7 8 3]]
[[1 1]
 [4 0]
 [7 3]]


In [41]:
print(a2) # list 자료형과 달리 배열의 슬라이스는 복사본이 아님. 별도로 만들려면 copy를 써야함.
print(a2[:2, :2])
a2_sub = a2[:2, :2]
a2_sub[:, 1] = 0
print(a2_sub)

[[1 0 1]
 [4 2 0]
 [7 8 3]]
[[1 0]
 [4 2]]
[[1 0]
 [4 0]]


In [42]:
print(a2)
a2_sub_copy = a2[:2, :2].copy() # 별개의 메모리에 저장이 된다!
print(a2_sub_copy)
a2_sub_copy[:, 1] = 1
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 3]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 0]
 [7 8 3]]


In [43]:
# 배열 변환
print(a2)
print(a2.T)
print(end = "\n\n")
print(a3)
print(end = "\n\n")
print(a3.T)

[[1 0 1]
 [4 0 0]
 [7 8 3]]
[[1 4 7]
 [0 0 8]
 [1 0 3]]


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


[[[1 1 1]
  [4 4 4]]

 [[2 2 2]
  [5 5 5]]

 [[3 3 3]
  [6 6 6]]]


In [44]:
print(a2)
print(a2.swapaxes(1, 0))

[[1 0 1]
 [4 0 0]
 [7 8 3]]
[[1 4 7]
 [0 0 8]
 [1 0 3]]


In [45]:
print(a3)
print(a3.shape)
print(end = "\n\n")
print(a3.swapaxes(0, 1))
print(end = "\n\n")
print(a3.transpose(1, 0, 2))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(3, 2, 3)


[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]]


[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]]


In [46]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3, 3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])
print(n1[np.newaxis, 3])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[4]


In [48]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
n2.resize(5, 2)
print(n2)
print(n2.reshape(2, 5))
print(n2)

[[0 0 3 7 9]
 [9 1 3 1 6]]
[[0 0]
 [3 7]
 [9 9]
 [1 3]
 [1 6]]
[[0 0 3 7 9]
 [9 1 3 1 6]]
[[0 0]
 [3 7]
 [9 9]
 [1 3]
 [1 6]]


In [49]:
n2.resize(2, 5)
print(n2)

[[0 0 3 7 9]
 [9 1 3 1 6]]


In [50]:
n2.reshape(5, 2)

array([[0, 0],
       [3, 7],
       [9, 9],
       [1, 3],
       [1, 6]])

In [51]:
n2.resize((5, 5), refcheck = False)
print(n2)
n2.resize((3, 3), refcheck = False)
print(n2)

[[0 0 3 7 9]
 [9 1 3 1 6]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 3]
 [7 9 9]
 [1 3 1]]


In [52]:
a2 = np.arange(1, 10).reshape(3, 3)
b2 = np.arange(10, 19).reshape(3, 3)
print(a2)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [53]:
c2 = np.append(a2, b2, axis = 1) # axis를 지정해주지 않으면 ndim이 1로 바뀜
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [54]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
np.append(a2, a2, axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [55]:
np.concatenate([a2, a2], axis = 1) # concatenate는 3개 이상 붙일 수 있음

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [56]:
print(a2)

[[1 2 3]
 [4 5 6]]


In [57]:
np.vstack([a2, a2]) # ndim = 1

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [58]:
np.hstack([a2, a2]) # ndim = 2

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [59]:
np.dstack([a2, a2])# ndim = 3

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

In [60]:
np.stack([a2, a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [61]:
# split: 배열 분할

a1 = np.arange(3, 15)
print(a1)
b1, c1 = np.split(a1, [5])
print(b1, c1)
b1, c1, d1, e1, f1 = np.split(a1, [2, 4, 6, 8])
print(b1, c1, d1, e1)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
[3 4 5 6 7] [ 8  9 10 11 12 13 14]
[3 4] [5 6] [7 8] [ 9 10]


In [62]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


In [63]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.hsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


In [64]:
a2 = np.arange(1, 28).reshape(3, 3, 3)
print(a3)
b3, c3 = np.dsplit(a3, [2])
print(b3)
print(c3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
[[[1 2]
  [4 5]]

 [[1 2]
  [4 5]]

 [[1 2]
  [4 5]]]
[[[3]
  [6]]

 [[3]
  [6]]

 [[3]
  [6]]]


In [65]:
a1 = np.arange(1, 10).reshape(3, 3)
b2 = np.array([1, 2, 3]).resshape(3, 1)
print(a1 + b2)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [66]:
a1 = np.arange(1, 10)
print(a1)
print(a1 + 1)
print(np.add(a1, 10))

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]


In [67]:
print(np.subtract(a1, -2))

[ 3  4  5  6  7  8  9 10 11]


In [68]:
print(np.negative(a1))
print(np.multiply(a1, 2))
print(np.divide(a1, 2))
print(a1 // 2) # floor_divide 내림....
print(np.floor_divide(a1, 2))

[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]


In [69]:
print(np.power(a1, 2)) # 지수

[ 1  4  9 16 25 36 49 64 81]


In [70]:
print(np.mod(a1, 2)) # 나머지

[1 0 1 0 1 0 1 0 1]


In [71]:
print(a1 % 2) # 나머지

[1 0 1 0 1 0 1 0 1]


In [72]:
a1 = np.arange(1, 10)
b1 = np.random.randint(1, 10, size = 9)
print(a1)
print(b1)

[1 2 3 4 5 6 7 8 9]
[5 9 7 6 1 5 5 4 8]


In [73]:
print(a1 + b1)
print(a1 - b1)
print(a1 / b1)
print(a1 // b1)
print(a1 ** b1)
print(a1 % b1)

[ 6 11 10 10  6 11 12 12 17]
[-4 -7 -4 -2  4  1  2  4  1]
[0.2        0.22222222 0.42857143 0.66666667 5.         1.2
 1.4        2.         1.125     ]
[0 0 0 0 5 1 1 2 1]
[       1      512     2187     4096        5     7776    16807     4096
 43046721]
[1 2 3 4 0 1 2 0 1]


In [74]:
a1 = np.random.randint(-10, 10, size = 5)
print(a1)
print(np.abs(a1))

[  1 -10   7  -8   2]
[ 1 10  7  8  2]


In [75]:
print(a1)
print(np.square(a1))
print(np.sqrt(np.abs(a1)))

[  1 -10   7  -8   2]
[  1 100  49  64   4]
[1.         3.16227766 2.64575131 2.82842712 1.41421356]


In [76]:
a1 = np.random.randint(1, 10, size = 5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))

[7 9 1 9 7]
[1.09663316e+03 8.10308393e+03 2.71828183e+00 8.10308393e+03
 1.09663316e+03]
[128. 512.   2. 512. 128.]


In [79]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[7 9 1 9 7]
[1.94591015 2.19722458 0.         2.19722458 1.94591015]
[2.80735492 3.169925   0.         3.169925   2.80735492]
[0.84509804 0.95424251 0.         0.95424251 0.84509804]


In [86]:
t = np.linspace(0, np.pi, 3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [88]:
a2 = np.random.randint(1, 10, size = (3, 3))
print(a2)
print(a2.sum())
print(np.sum(a2))
print(a2.sum(axis = 0)) # axis를 기반으로
print(np.sum(a2, axis = 1)) # axis를 기반으로

[[8 4 7]
 [4 9 5]
 [2 3 7]]
49
49
[14 16 19]
[19 18 12]


In [91]:
print(a2)
print(np.cumsum(a2)) # cumulative sum
print(np.cumsum(a2, axis = 1))

[[8 4 7]
 [4 9 5]
 [2 3 7]]
[ 8 12 19 23 32 37 39 42 49]
[[ 8 12 19]
 [ 4 13 18]
 [ 2  5 12]]


In [94]:
print(a2)
print(np.diff(a2))
print(np.diff(a2, axis = 0))
print(np.diff(a2, axis = 1))

[[8 4 7]
 [4 9 5]
 [2 3 7]]
[[-4  3]
 [ 5 -4]
 [ 1  4]]
[[-4  5 -2]
 [-2 -6  2]]
[[-4  3]
 [ 5 -4]
 [ 1  4]]


In [96]:
print(a2)
print(np.prod(a2))
print(np.prod(a2, axis = 0))
print(np.prod(a2, axis = 1))

[[8 4 7]
 [4 9 5]
 [2 3 7]]
1693440
[ 64 108 245]
[224 180  42]


In [114]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2, axis = 0))
print(np.cumprod(a2, axis = 1))

[[8 4 7]
 [4 9 5]
 [2 3 7]]
[      8      32     224     896    8064   40320   80640  241920 1693440]
[[  8   4   7]
 [ 32  36  35]
 [ 64 108 245]]
[[  8  32 224]
 [  4  36 180]
 [  2   6  42]]


In [102]:
b2 = np.ones_like(a2)
print(a2)
print(b2)
print(a2 * b2)
print(np.dot(a2, b2)) # dot과 matmul이 동일하게 결과가 나옴
print(np.matmul(a2, b2)) # dot과 matmul이 동일하게 결과가 나옴

[[8 4 7]
 [4 9 5]
 [2 3 7]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[8 4 7]
 [4 9 5]
 [2 3 7]]
[[19 19 19]
 [18 18 18]
 [12 12 12]]
[[19 19 19]
 [18 18 18]
 [12 12 12]]


In [103]:
print(a2)
print(b2)
print(np.tensordot(a2, b2))

[[8 4 7]
 [4 9 5]
 [2 3 7]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
49


In [123]:
z2 = np.ones_like(a2)
print(a2)
print(z2)

print(np.tensordot(a2, z2, axes = 1))

[[8 4 7]
 [4 9 5]
 [2 3 7]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[19 19 19]
 [18 18 18]
 [12 12 12]]


In [109]:
8 * 2 + 4 * 6 + 7 * 2 + 4 * 6 + 9 * 2 + 5 * 2 + 2 + 15 + 14

137

In [130]:
aaa = np.arange(1, 5).reshape(2, 2)
bbb = np.arange(5, 9).reshape(2, 2)
print(aaa)
print(bbb)
print(end = "\n\n")
print(np.tensordot(aaa, bbb))
print(end = "\n\n")
print(np.tensordot(aaa, bbb, axes = 0))
print(end = "\n\n")
print(np.tensordot(aaa, bbb, axes = 1)) # dot과 같은 결과가 나온다
print(end = "\n\n")
print(np.dot(aaa, bbb))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


70


[[[[ 5  6]
   [ 7  8]]

  [[10 12]
   [14 16]]]


 [[[15 18]
   [21 24]]

  [[20 24]
   [28 32]]]]


[[19 22]
 [43 50]]


[[19 22]
 [43 50]]


In [132]:
# cross

x = [1, 2, 3]
y = [4, 5, 5]
print(np.cross(x, y)) # 2 * 5 - 3 * 5 + 3 * 4 - 1* 5 + 1 * 5 - 2* 4

[-5  7 -3]


In [135]:
# inner / outer

print(a2)
print(b2)
print(np.inner(a2, b2)) # inner, dot, matmul 전부 같다
print(np.dot(a2, b2)) # inner, dot, matmul 전부 같다
print(np.matmul(a2, b2)) # inner, dot, matmul 전부 같다
print(np.outer(a2, b2))

[[8 4 7]
 [4 9 5]
 [2 3 7]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[19 19 19]
 [18 18 18]
 [12 12 12]]
[[19 19 19]
 [18 18 18]
 [12 12 12]]
[[19 19 19]
 [18 18 18]
 [12 12 12]]
[[8 8 8 8 8 8 8 8 8]
 [4 4 4 4 4 4 4 4 4]
 [7 7 7 7 7 7 7 7 7]
 [4 4 4 4 4 4 4 4 4]
 [9 9 9 9 9 9 9 9 9]
 [5 5 5 5 5 5 5 5 5]
 [2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3]
 [7 7 7 7 7 7 7 7 7]]


In [136]:
print(aaa)
print(bbb)
print(np.outer(aaa, bbb))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]]


In [142]:
print(np.mean(a2))
print(np.mean(a2, axis = 0))
print(np.mean(a2, axis = 1))

5.444444444444445
[4.66666667 5.33333333 6.33333333]
[6.33333333 6.         4.        ]


In [145]:
print(a2)
print(np.std(a2))
print(np.var(a2))

[[8 4 7]
 [4 9 5]
 [2 3 7]]
2.2662308949301266
5.135802469135802


In [151]:
print(a2)
print(np.max(a2))
print(np.argmax(a2))
print(np.median(a2))
print(np.sum(a2))

[[8 4 7]
 [4 9 5]
 [2 3 7]]
9
4
5.0
49


In [153]:
a1 = np.array([0, 1, 2, 3])
print(a1)
print(np.percentile(a1, [0, 20, 40, 60, 80, 100]))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation = 'linear'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation = 'higher'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation = 'lower'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation = 'nearest'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation = 'midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


In [179]:
a2 = np.array([[0, 1, 0],
               [0, 1, 1],
               [0, 1, 1]])
a2_bool = a2.astype(np.bool)
print(a2_bool)
print(np.any(a2_bool)) # 이중 하나라도 true라면 true
print(np.any(a2_bool, axis = 0))
print(np.any(a2_bool, axis = 1))
print(np.all(a2_bool))
print(np.all(a2_bool, axis = 0))

[[False  True False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[ True  True  True]
False
[False  True False]


In [185]:
# comparision operators

a1 = np.arange(1, 10)
print(a1)
print(a1 == 5)
print(np.equal(a1, 5))
print(a1 != 5)
print(a1 < 5)
print(a1 > 5)
print(a1 >= 5)
print(a1 <= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]
[ True  True  True  True  True False False False False]


In [195]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2 > 5))
print(np.sum(a2 > 5, axis = 1))
print(np.any(a2 > 5))
print(np.all(a2 > 5, axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
[0 1 3]
True
[False False  True]


In [196]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
b1 = np.array([1, 2 ,3, 3, 4])
print(b1)
print(np.isclose(a1, b1)) # 배열 두개가 (z*1e+02)% 내외로 가까우면, True, 멀면 Flase

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [201]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


In [211]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print((a2 > 5) & (a2 < 8))
print(((a2 > 5) & (a2 < 8)).reshape(-1,))
print(a2[(a2 > 5) & (a2 < 8)])
print((a2 > 5) | (a2 < 8)) # OR
print((a2 > 5) ^ (a2 < 8)) # XOR
print(a2 > 5)
print(~(a2 > 5)) # NO

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[False False False False False  True  True False False]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[[False False False]
 [False False  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True False]
 [False False False]]


In [215]:
a1 = np.random.randint(1, 10, size = 10)
print(a1)
print(np.sort(a1))
print(np.argsort(a1)) # 위치값만
a1.sort()
print(a1)

[5 8 9 8 1 9 9 5 6 6]
[1 5 5 6 6 8 8 9 9 9]
[4 0 7 8 9 1 3 2 5 6]
[1 5 5 6 6 8 8 9 9 9]


In [218]:
a2 = np.random.randint(1, 10, size = (3, 3))
print(a2)
print(np.sort(a2))
print(np.sort(a2, axis = 0))
print(np.sort(a2, axis = 1))

[[1 6 4]
 [7 5 2]
 [6 5 8]]
[[1 4 6]
 [2 5 7]
 [5 6 8]]
[[1 5 2]
 [6 5 4]
 [7 6 8]]
[[1 4 6]
 [2 5 7]
 [5 6 8]]


In [233]:
# partition 부분 정렬
a1 = np.arange(1, 10)[::-1]
print(a1)
print(np.partition(a1, 0))

[9 8 7 6 5 4 3 2 1]
[1 8 7 6 5 4 3 2 9]


In [245]:
a2 = np.random.randint(1, 10, size = (5, 5))
print(a2)
np.save("a", a2)

[[4 6 9 6 4]
 [6 2 8 9 9]
 [6 6 7 1 1]
 [8 3 8 7 2]
 [3 4 1 8 7]]


In [248]:
b2 = np.random.randint(1, 10, size = (5, 5))
print(b2)
np.savez("ab", a2, b2)

[[9 3 9 4 1]
 [7 1 3 4 7]
 [1 2 1 2 9]
 [5 6 2 6 8]
 [1 9 8 4 9]]


In [249]:
npy = np.load("a.npy")
print(npy)

[[4 6 9 6 4]
 [6 2 8 9 9]
 [6 6 7 1 1]
 [8 3 8 7 2]
 [3 4 1 8 7]]


In [256]:
npz = np.load("ab.npz")
print(npz)
print(npz.files)
print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[4 6 9 6 4]
 [6 2 8 9 9]
 [6 6 7 1 1]
 [8 3 8 7 2]
 [3 4 1 8 7]]
[[9 3 9 4 1]
 [7 1 3 4 7]
 [1 2 1 2 9]
 [5 6 2 6 8]
 [1 9 8 4 9]]


In [281]:
print(a2)
np.savetxt("a.csv", a2, delimiter = ",")

[[4 6 9 6 4]
 [6 2 8 9 9]
 [6 6 7 1 1]
 [8 3 8 7 2]
 [3 4 1 8 7]]


In [307]:
csv = np.loadtxt("a.csv", delimiter = ",")
print(csv)

[[4. 6. 9. 6. 4.]
 [6. 2. 8. 9. 9.]
 [6. 6. 7. 1. 1.]
 [8. 3. 8. 7. 2.]
 [3. 4. 1. 8. 7.]]


In [311]:
print(b2)
np.savetxt("b.csv", b2, delimiter = ",", fmt = "%.2e", header = "c1, c2, c3, c4, c5")
csv = np.loadtxt("b.csv", delimiter = ",")
print(csv)

[[9 3 9 4 1]
 [7 1 3 4 7]
 [1 2 1 2 9]
 [5 6 2 6 8]
 [1 9 8 4 9]]
[[9. 3. 9. 4. 1.]
 [7. 1. 3. 4. 7.]
 [1. 2. 1. 2. 9.]
 [5. 6. 2. 6. 8.]
 [1. 9. 8. 4. 9.]]
